// <auto-generated />
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230213070658_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityLayer.Concrete.Aidat", b =>
                {
                    b.Property<int>("AidatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AidatAYLAR")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AidatID");

                    b.ToTable("Aidats");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CategoryStatus")
                        .HasColumnType("bit");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Daire", b =>
                {
                    b.Property<int>("DaireID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BlokNUMARA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DaireACIKLAMA")
                        .HasColumnType("int");

                    b.Property<int>("DaireALAN")
                        .HasColumnType("int");

                    b.Property<int>("DaireKAT")
                        .HasColumnType("int");

                    b.Property<string>("DaireNUMARA")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DaireID");

                    b.ToTable("Daires");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Gider", b =>
                {
                    b.Property<int>("GiderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GiderFirma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GiderTUR")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GiderID");

                    b.ToTable("Giders");
                });

            modelBuilder.Entity("EntityLayer.Concrete.KiraciMalSahibi", b =>
                {
                    b.Property<int>("KiraciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KiraciADSOYAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KiraciMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KiraciTelefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SahibADSOYAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SahibID")
                        .HasColumnType("int");

                    b.Property<string>("SahibMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SahipTelefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KiraciID");

                    b.ToTable("KiraciMalSahibis");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Site", b =>
                {
                    b.Property<int>("SiteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SiteAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteADRES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteISITUR")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SiteID");

                    b.ToTable("Sites");
                });
#pragma warning restore 612, 618
        }
    }
}
